# GlobalMC-cmdDisable by RaceAgainstTime
# https://github.com/It-is-Dan
# Made for GlobalMC
command-deny-message: '&cYou dont have permission to use that command!'

disabled-commands:
  - pl
  - plugins
  - ver
  - version
  - "?"
  - about
  - icanhasbukkit
  - bukkit:ver
  - bukkit:plugins
  - bukkit:version
  - bukkit:help
  - bukkit:about
  - bukkit:?
  - bukkit:pl
